const Wilaya = [
{'name':'Adrar'},
{'name':'Chlef'},
{'name':'Laghouat'},
{'name':'Oum El Bouaghi'},
{'name':'Batna'},
{'name':'Béjaïa'},
{'name':'Biskra'},
{'name':'Béchar'},
{'name':'Blida'},
{'name':'Bouira'},
{'name':'Tamanrasset'},
{'name':'Tébessa'},
{'name':'Tlemcen'},
{'name':'Tiaret'},
{'name':'Tizi Ouzou'},
{'name':'Alger'},
{'name': 'Djelfa'},
{'name': 'Jijel'},
{'name': 'Sétif'},
{'name': 'Saïda'},
{'name': 'Skikda'},
{'name': 'Sidi Bel Abbès'},
{'name': 'Annaba'},
{'name': 'Guelma'},
{'name': 'Constantine'},
{'name': 'Médéa'},
{'name': 'Mostaganem'},
{'name': 'M\'Sila'},
{'name': 'Mascara'},
{'name': 'Ouargla'},
{'name': 'Oran'},
{'name': 'El Bayadh'},
{'name': 'Illizi'},
{'name': 'Bordj Bou Arreridj'},
{'name': 'Boumerdès'},
{'name': 'El Tarf'},
{'name': 'Tindouf'},
{'name': 'Tissemsilt'},
{'name': 'El Oued'},
{'name': 'Khenchela'},
{'name': 'Souk Ahras'},
{'name': 'Tipaza'},
{'name': 'Mila'},
{'name': 'Aïn Defla'},
{'name': 'Wilaya de Naâma'},
{'name': 'Aïn Témouchent'},
{'name': 'Ghardaïa'},
{'name': 'Relizane'}
]

export default Wilaya;